# Generated by Django 2.2.1 on 2019-09-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygarments', '0003_auto_20190920_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('formalshirt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mygarments.FormalShirt')),
            ],
            bases=('mygarments.formalshirt',),
        ),
    ]
