# Generated by Django 2.2.1 on 2019-10-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygarments', '0004_tshirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeanes',
            fields=[
                ('formalshirt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mygarments.FormalShirt')),
            ],
            bases=('mygarments.formalshirt',),
        ),
    ]
